
# - apt: name=tilix
#   become: yes

# - alternatives:
#     name: x-terminal-emulator
#     path: /usr/bin/tilix.wrapper
#   become: yes

- name: tilix configuration
  dconf: key='{{ item.key }}' value='{{ item.value | string }}'
  with_items:
    # open new session in existing window
    - key: /com/gexperts/Tilix/new-instance-mode
      value: "'new-session'"

# https://gnunn1.github.io/tilix-web/manual/vteconfig/

# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding
#   '<Super>t'
# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command
#   'tilix'
# /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name
#   'Tilix'
