
- name: install flatpak
  apt: name=flatpak state=present
  become: yes

- name: add flathub
  flatpak_remote:
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    name: "flathub"
  become: yes

- name: add flatpak remotes
  flatpak_remote:
    flatpakrepo_url: "{{ item.url }}"
    name: "{{ item.name }}"
  with_items: "{{ flatpak_remotes }}"
  become: yes

- name: list installed flatpaks
  shell: flatpak list --columns=application
  register: flatpaks_installed
  changed_when: false

- name: install flatpak packages
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote.name | default('flathub') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ flatpaks }}"
  when: flatpaks is defined and not item.name in flatpaks_installed.stdout_lines
  become: yes

- name: override filesystem access
  shell: "flatpak override {{ item.name }} --filesystem={{ item.filesystem }}"
  become: yes
  changed_when: false
  with_items: "{{ flatpak_filesystems }}"
