
- name: install snap packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default('no') }}"
    channel: "{{ item.channel | default('stable') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ snaps }}"
  become: yes

- name: remove disabled snaps
  shell: |
    snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done
  become: yes
  changed_when: False
