- stat: path="{{ user_home_dir }}/.asdf/bin/asdf"
  register: asdf_exists_result

- apt: name=build-essential status=present
  become: yes

- import_role: name=cimon-io.asdf
  vars:
    asdf_version: v0.7.8
    asdf_user: "{{ user_name }}"
    asdf_plugins: "{{ sdks }}"
  # when: asdf_exists_result == False

- name: configure asdf bashrc
  blockinfile:
    path: '{{ user_home_dir }}/.bashrc'
    marker: '# {mark} ASDF BASH'
    block: |
      if [ -f "$HOME/.asdf/asdf.sh" ]; then
        source $HOME/.asdf/asdf.sh
        source $HOME/.asdf/completions/asdf.bash
      fi
