- file: path='{{ item }}' state=directory
  with_items:
    - '{{ gnome_extensions_dir }}'

- get_url:
    url: "{{ appindicators_url }}"
    dest: "{{ appindicators_file }}"

- unarchive:
    src: '{{ appindicators_file }}'
    dest: '{{ gnome_extensions_dir }}'
