user_home_dir: "{{ ansible_env.HOME }}"
user_config_dir: "{{ user_home_dir }}/.config"
user_local_dir: "{{ user_home_dir }}/.local"
download_dir: "{{ user_home_dir }}/.ansible/tmp/downloads"
temp_dir: "{{ user_home_dir }}/.ansible/tmp"
desktop_app_dir: "{{ user_local_dir }}/share/applications"

github_dir: "{{ user_home_dir }}/Github"

local_fonts: "{{ user_local_dir }}/share/fonts"
