
- name: install onedrive
  apt:
    name:
      - onedrive
  become: yes

- file: path="{{ item }}" state=directory
  with_items:
    - "{{ user_config_dir }}/onedrive"
    - "{{ user_home_dir }}/OneDrive"

- name: copy config
  copy:
    src: "{{ item }}"
    dest: "{{ user_config_dir }}/onedrive/{{ item }}"
    force: no
  with_items:
    - config
    - sync_list
