- name: read wallpaper
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    state: read
  register: current_wallpaper

- name: replace desktop wallpaper
  when: '"warty-final-ubuntu.png" in current_wallpaper.value'
  dconf: key='{{ item.key }}' value='{{ item.value }}'
  with_items:
    # background
    - key: '/org/gnome/desktop/background/color-shading-type'
      value: "'solid'"
    - key: '/org/gnome/desktop/background/picture-options'
      value: "'zoom'"
    - key: '/org/gnome/desktop/background/picture-uri'
      value: "'file:///usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png'"
    - key: '/org/gnome/desktop/background/primary-color'
      value: "'#333333'"
    - key: '/org/gnome/desktop/background/secondary-color'
      value: "'#333333'"
    # lockscreen
    - key: '/org/gnome/desktop/screensaver/color-shading-type'
      value: "'solid'"
    - key: '/org/gnome/desktop/screensaver/picture-options'
      value: "'zoom'"
    - key: '/org/gnome/desktop/screensaver/picture-uri'
      value: "'file:///usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png'"
    - key: '/org/gnome/desktop/screensaver/primary-color'
      value: "'#333333'"
    - key: '/org/gnome/desktop/screensaver/secondary-color'
      value: "'#333333'"
