
# repo_packages: "{{ packages | json_query(\"[?type=='repo']\") | list }}"
repo_keys: "{{ packages | json_query('[?key]') | map(attribute='key') | list | sort | unique }}"
repo_urls: "{{ packages | json_query('[?repo]') | map(attribute='repo') | list | sort | unique }}"
ppa_repos: "{{ packages | json_query('[?ppa]') | map(attribute='ppa') | list | sort | unique }}"
