- include_vars: "ubuntu.yml"
- include_tasks: 'gnome/extensions/gtktitlebar.yml'

- name: replace desktop wallpaper
  dconf: key='{{ item.key }}' value='{{ item.value | string }}'
  with_items:
    # system
    - key: /org/gnome/desktop/interface/show-battery-percentage
      value: "true"
    - key: /org/gnome/desktop/input-sources/sources
      value: "[('xkb', 'us'), ('xkb', 'cz')]"
    # single click open in nautilus
    - key: /org/gnome/nautilus/preferences/click-policy
      value: "'single'"
    # media shortcuts
    - key: /org/gnome/settings-daemon/plugins/media-keys/play
      value: "['<Alt><Super>Down']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/volume-up
      value: "['<Primary><Alt><Super>Up']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/volume-down
      value: "['<Primary><Alt><Super>Down']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/next
      value: "['<Alt><Super>Right']"
    - key: /org/gnome/settings-daemon/plugins/media-keys/previous
      value: "['<Alt><Super>Left']"
