- apt:
    name:
      - neomutt
      - offlineimap
      - w3m
      - libnotify-bin
      - notmuch
  become: yes

- apt:
    name: notmuch-mutt
    install_recommends: no
  become: yes

# https://babushk.in/posts/offlineimap-systemd.html

- file: path="{{ item }}" state=directory
  with_items:
    - "{{ user_config_dir }}/systemd/user"

- name: configure offlineimap service
  copy: src="{{ item }}" dest="{{ user_config_dir }}/systemd/user/{{ item }}"
  with_items:
    - offlineimap.service
    - offlineimap.timer

- name: enable offlineimap service
  systemd:
    name: offlineimap.timer
    enabled: yes
    user: yes

# configure notmuch

# html preview - copy file first, return asap, delete on close

# geary:
# $ curl https://gitlab.gnome.org/GNOME/gnome-keyring/raw/ff229abca62db366c84dfe58035324f6d8ca6059/pkcs11/rpc-layer/gnome-keyring.module.in > ~/.config/pkcs11/modules/gnome-keyring.module
