---

- name: clone bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: '{{ user_home_dir }}/.bash-git-prompt'

- name: configure bash
  blockinfile:
    path: '{{ user_home_dir }}/.bashrc'
    block: |
      if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
          GIT_PROMPT_ONLY_IN_REPO=0
          GIT_PROMPT_SHOW_UPSTREAM=1
          GIT_PROMPT_END_USER=" \n${ResetColor}$ "
          GIT_PROMPT_THEME=Default
          source $HOME/.bash-git-prompt/gitprompt.sh
      fi
