---

- hosts: ubuntu_at_work
  vars_files:
    - group_vars/ubuntu.yml
    - group_vars/ubuntu_at_work.yml
    - secrets.yml
  roles:
    - role: essentials
    # - role: onedrive
    # - role: gnome
    #   nautilus_bookmarks:
    #     - "{{ user_home_dir }}/Workspace"
    #     - "{{ user_home_dir }}/OneDrive"
    #     - "{{ user_home_dir }}/Dropbox"
    # - role: pop-theme
    # - role: tilix
    # - role: git
    # - role: asdf
    # - role: docker
    # - role: sublime
    # - role: code
    # - role: intellij
    # - role: mutt
    # - role: datovka
    # - role: gantsign.ctop
    # - role: jetbrains-mono
    # - role: xps
    # - role: fma
    # - role: aws
    - role: advcpmv

- hosts: debian_at_home
  vars_files:
    - group_vars/debian.yml
    - group_vars/debian_at_home.yml
    - secrets.yml
  roles:
    - role: essentials
    - role: keepass
      keepass_sync: no
    - role: jetbrains-mono
      #- role: sublime
    - role: tilix
    - role: emma-desktop
    - role: l502x
    - role: advcpmv

- hosts: pop_at_work
  vars_files:
    - group_vars/ubuntu.yml
    - group_vars/pop_at_work.yml
    - secrets.yml
  roles:
    # - role: snap
    - role: essentials
    # - role: sublime
    # - role: gantsign.ctop
    # - role: intellij
    # - role: asdf
    #   asdf_user: "{{ user_name }}"
    #   asdf_plugins:
    #     - name: "java"
    #       versions:
    #         - 'adopt-openjdk-11.0.7+10'
    #         - 'adopt-openjdk-8u252-b09'
    #       global: 'adopt-openjdk-11.0.7+10'
    #     - name: "nodejs"
    #       versions:
    #         - '12.16.3'
    #       global: '12.16.3'
    #     - name: "maven"
    #       versions:
    #         - '3.6.3'
    #       global: '3.6.3'
    #     - name: "github-cli"
    #       versions:
    #         - '0.7.0'
    #       global: '0.7.0'
    # - role: docker
    # - role: tilix
    # - role: brave
    # - role: git
    # - role: desktop
    - role: mutt
