- include_role:
    name: yum-repos
  vars:
    rpm_repos:
      - name: sublime
        url: https://download.sublimetext.com/rpm/stable/x86_64
        key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

- include_role:
    name: ostree-packages
  vars:
    packages:
      - name: sublime-text
      - name: sublime-merge

# - name: create preferences directories
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#     - "{{ sublime_text_config_dir }}"
#     - "{{ sublime_merge_config_dir }}"

# - name: configure sync settings
#   include_tasks: sync-settings.yml
#   when: sublime_text_sync_settings|default(false)|bool == true

# - name: sublime merge settings
#   copy:
#     src: merge_Preferences.sublime-settings
#     dest: "{{ sublime_merge_config_dir }}/Preferences.sublime-settings"
#     force: no
